// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIjoYG-6zQ_gXYlAdq3GHYtcHNMzw-jvg',
    appId: '1:496656649640:web:0af3d45b3d731a9f16619d',
    messagingSenderId: '496656649640',
    projectId: 'flutter-mynimelist',
    authDomain: 'flutter-mynimelist.firebaseapp.com',
    storageBucket: 'flutter-mynimelist.appspot.com',
    measurementId: 'G-5V71MTCQE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrttao6dFdi7YEyvlECB89bWgBmwuag84',
    appId: '1:496656649640:android:93a6c4ece71cfb1516619d',
    messagingSenderId: '496656649640',
    projectId: 'flutter-mynimelist',
    storageBucket: 'flutter-mynimelist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAckAfbZS8qMJefdbyPw0FiaWjFPN1HbSE',
    appId: '1:496656649640:ios:fef3311e437b8ad716619d',
    messagingSenderId: '496656649640',
    projectId: 'flutter-mynimelist',
    storageBucket: 'flutter-mynimelist.appspot.com',
    iosBundleId: 'com.example.flutterListAnime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAckAfbZS8qMJefdbyPw0FiaWjFPN1HbSE',
    appId: '1:496656649640:ios:6ce505a002ece7da16619d',
    messagingSenderId: '496656649640',
    projectId: 'flutter-mynimelist',
    storageBucket: 'flutter-mynimelist.appspot.com',
    iosBundleId: 'com.example.flutterListAnime.RunnerTests',
  );
}
